from __future__ import annotations

from typing import Protocol

from .metadata import BlockKey, BlockLocation, KVMetadata, LoadResult, StoreResult, TierName


class Tier(Protocol):
    name: TierName

    def lookup(self, key: BlockKey) -> BlockLocation | None: ...

    def store(self, key: BlockKey, data: bytes, metadata: KVMetadata) -> StoreResult: ...

    def load(self, key: BlockKey) -> LoadResult: ...

    def evict(self, key: BlockKey) -> bool: ...

    def contains(self, key: BlockKey) -> bool: ...

    def stats(self) -> dict: ...


class KVBlockStore(Protocol):
    def lookup(self, key: BlockKey) -> BlockLocation | None: ...

    def store(self, key: BlockKey, data: bytes, metadata: KVMetadata, preferred_tier: TierName | None = None) -> StoreResult: ...

    def load(self, key: BlockKey, target_tier: TierName = TierName.MEMORY, slo_budget_ms: float | None = None) -> LoadResult: ...

    def prefetch(self, keys: list[BlockKey], target_tier: TierName = TierName.MEMORY) -> None: ...

    def evict(self, key: BlockKey, tier: TierName | None = None) -> bool: ...

    def release(self, key: BlockKey) -> None: ...

    def stats(self) -> dict: ...
